plugins {
    id 'application'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

run {
    standardInput = System.in
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.mockito:mockito-core:5.11.0'
}

test {
    useJUnitPlatform()
}

application {
    mainClass = 'src/main/java/de/dhbw/Main.java' // z.B. com.example.Main
}