@startuml Aggregates

class Instruction {
  - keyword: String
  - instructionValues: InstructionValue[]
}

class InstructionValue {
  - address: Address
  - word: Word
}

class Register {
  - storageSpaces: StorageSpace[]
}

class StorageSpace {
  - address: Address
  - word: Word
}

class ControlUnit {
  - decoder: Decoder
  - processingUnits: ProcessingUnit[]
  - storageManager: StorageManager
  - storedValue: Word
}

Instruction --> InstructionValue
InstructionValue --> Address
InstructionValue --> Word

Register --> StorageSpace
StorageSpace --> Address
StorageSpace --> Word

ControlUnit --> Decoder
ControlUnit --> ProcessingUnit
ControlUnit --> StorageManager
ControlUnit --> Word : storedValue

@enduml