@startuml

interface OutputHandler {
    +print(text: String): void
}

class OutputHandlerImpl {
    -printStream: PrintStream
    +OutputHandlerImpl()
    +print(text: String): void
}

OutputHandlerImpl ..|> OutputHandler

@enduml
